### ISSUE TITLE
Major version changes on dependencies could cause issues 

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1029]
Previously we had discussed whether we would want to fix all our versions in setup.py but there was good points made that we don't want to restrict versions especially to avoid introducing limitations of Seldon core when being installed with other libraries. However we could pick up the conversation again and explore whether limiting only on major versions would make sense as it would be major versions that could come with breaking changes. Furthermore @adriangonz actually suggested that he was going to have a look at @dependabot which automatically would flag packages that may require updates, which could make sure we get the best of both worlds; safety of fixed major versions but automated push to stay up to date with latest.

**Comment by adriangonz** [comment]
I set up `dependabot` on my personal fork of the repo and it seems to be pretty cool! It detects if the max version is too restricted and it allows you to specify different folders with different languages. It also pulls the changelogs of each package update so that you can check directly in the PR if there are any breaking things you should pay attention to.

You can have a look at the PRs `dependabot` created on my personal fork here https://github.com/adriangonz/seldon-core/pulls.

What do you guys think? Should we set it up on `seldon-core`?

**Comment by axsaucedo** [comment]
Very cool! It even suggests adding Major version limits (i.e. tensorflow) - I think it would be worth setting up, although I'm not sure whether it could become a bit too many PR requests if we set it up for patch versions. Is it possible to set it up for minor versions only perhaps? Awesome work tho, looks great on the repo!
