### ISSUE TITLE
Missing binaries for grpcio 1.27

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1409]
The `1.27.0` release of `grpcio` doesn't seem to provide wheels on some platforms. This forces some users who install `seldon-core` to build it themselves and to have around all the dev tooling necessary (i.e. `gcc`, `python-devel`, headers, etc.). A similar issue is reported here: https://github.com/grpc/grpc/issues/21918 .

The change seems related to dropping support for the `manylinux1` spec, which is discussed on the following issue: https://github.com/grpc/grpc/pull/21790

**Comment by adriangonz** [comment]
As a temporary workaround we can upper limit the `grpcio` version to `1.26.0`, which did provide these wheels:

https://github.com/SeldonIO/seldon-core/blob/a72257fa851033ee09513a0b6b310087eb625e85/python/setup.py#L35

**Comment by lidizheng** [comment]
@adriangonz Can you give more details about the platform? Generally, PyPI packages can't be installed directly on Alpine-based system since it is not `manylinux1` compatible. On the other hand, if you are not using Alpine-based system, you can upgrade your `pip` to at least `19.0.0` to let it recognize `manylinux2010` wheels.

```
pip install -U pip
```

**Comment by adriangonz** [comment]
Thanks @lidizheng! You are right, the issue seems to be caused by an old version of `pip`. After updating it, the problem has gone away.
