### ISSUE TITLE
Update Kubeflow Example to 1.0

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1509]
It would be good to update our current Kubeflow example to use 1.0, as well as add a page on the Seldon Docs on "Kubeflow Integration".  If possible it would also be good to update it to leverage prepackaged model servers  instead of the reusable containers as that is now the way that we're looking to integrate with model training frameworks. Example: https://docs.seldon.io/projects/seldon-core/en/latest/examples/kubeflow_seldon_e2e_pipeline.html

**Comment by vega42** [comment]
Hey Alejandro, I'm looking at this issue. I see the requirements.txt is hardwired to kfp v0.1.20. I'm assuming this is part of the legacy update required?

**Comment by vega42** [comment]
Hey Alejandro, I'm trying to understand the objective a little better. Are you proposing to rewrite the E2E pipeline doc shared above to support prepackaged model servers? 

I also found this:

https://docs.seldon.io/projects/seldon-core/en/latest/analytics/kubeflow.html

Do you envision expanding on it?

**Comment by ryandawsonuk** [comment]
@vega42 if you’re interested in this then also worth looking at https://github.com/kubeflow/pipelines/tree/master/samples/contrib/seldon as that shows a prepackaged server example, as well as others. But the seldon repo one is more E2E. I think the main thing would be to see if the examples work with latest kubeflow as there have been changes on the kubeflow side since.
