### ISSUE TITLE
Document compatbility of wrapper versions with seldon engine versions

### ISSUE THREAD

**Issue by kparaju** [SeldonIO/seldon-core#1564]
When we upgrade the seldon operator which upgrades the seldon engine, we might have docker images that are build with an older python wrapper. Adding a compatibility table of seldon engine and the different wrappers with upgrade notes would be really helpful. Something like:

| Engine|Python Wrapper|Java Wrapper |Supported | Notes | 
|-------|:---------------:|--------------:|-----------:|--------------------:|
|0.4.2   |<1.0|?|✅| |
|1.1   |<1.0|?|❌| |

We can start off with something like this and maybe add another column that differentiates between "it works" vs "it works but it's deprecated"

**Comment by amoldavsky** [comment]
Hi, Assaf from Jobcase here, we are planning to upgrade from Seldon-Core 0.1 to 1.0 and we are using Java wrapper 0.1.5. We have a concern that the upgrade may result in us having to shut down the entire cluster because non of the Java wrapper will be compatible with the new version of Seldon-Core. 

@adriangonz @axsaucedo @cliveseldon

**Comment by cliveseldon** [comment]
This is in progress - we will close when available in docs.
https://github.com/SeldonIO/seldon-core/blob/master/doc/source/reference/upgrading.md

We will only show >=1.0 compatibility
