### ISSUE TITLE
Different behaviors between seldon-engine v0.4.1 and v1.0.2

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#1569]
We have a model, if we call it directly it will response

`
"data": {"names": ["id", "score"], "ndarray": [["111416", 7668.0], ["15647517", 0.0]]
`

For seldon-engine v0.4.1, we got the expected data returned for the client.
`
"data": {"names": ["id", "score"], "ndarray": [["111416", 7668.0], ["15647517", 0.0]]
`
but after upgrade to seldon-engine v1.0.2, it auto convert float number 7668.0 -> 7668

instead we got the following response:
`"data": { "names": ["id", "score"], "ndarray": [["111416", 7668], ["15647517", 0]]`

It feels like a bug

**Comment by cliveseldon** [comment]
Thanks for the report. A few questions?

How was your model defined? 
If via the python wrapper- which version of the python wrapper builder image did you use if S2I or which version of the python module?
Does the model itself return a float or int?
Do you use REST or gRPC?
Which python class method do you use? predict or predict_raw?

**Comment by anggao** [comment]
1. we tested with both python wrapper module version v0.4.1 and v1.0.2, same problem.
2. The model itself returns a float, if we call the model directly we saw values like `7668.0`
3. We use REST
4. We use predict_raw method

**Comment by cliveseldon** [comment]
This should be definitely be fixed in 1.1 if you use the executor. You can test if you run from master.

Quite some work was done to try to ensure this did not happen. See:
https://docs.seldon.io/projects/seldon-core/en/v1.0.2/python/python_component.html#integer-numbers

Its not clear right now why this doesn't work.

**Comment by anggao** [comment]
Thanks, I think the conversion happened within seldon-engin (java), not sure why. it seems there are some libraries upgrade between v0.41 -> v1.0.2

**Comment by adriangonz** [comment]
We decided it to do it this way on the Java engine to fix the opposite situation. That is, if you passed an integer it would always convert it to a floating point number. For example, `{"vocab_length": 27}` would always get read by the engine (and serialised downstream) as `{"vocab_length": 27.0}`.

This is a limitation of the `google.protobuf.Value` type we use underneath which doesn't differentiate between integers and floating point numbers to be aligned with JSON. Even though this is protobuf, it still applied to the REST use case because the Java engine would always try to parse and read the input message. 

The executor should handle this much better. @anggao if you could have a look at the version in `master` it would be great to have your feedback!

**Comment by anggao** [comment]
Thanks for the info! I tested engine `docker.io/seldonio/seldon-core-executor:1.0.3-SNAPSHOT` and it works as expected. e.g. the number `11590.0` still keeps float in the client response

**Comment by cliveseldon** [comment]
Fixed in next release 1.1 (1.0.3-SNAPSHOT)
