### ISSUE TITLE
Multiplex Http and gRPC traffic

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1628]
In the new executor and SeldonDeployment graphs one chooses http or grpc.
Can we handle both:

  * Multiplex http and grpc on the executor: see https://github.com/knative/serving/issues/7140
  * Multiplex on language wrapperor always expose both: python 
  * Check all language servers handle both or multiplex
     * TFServing handles both
     * Triton handles both
 * Expose both endpoints always on supported ingress

**Comment by gaocegege** [comment]
@glindsell Hi, is there any progress?

**Comment by glindsell** [comment]
Hi @gaocegege will take a look and let you know

**Comment by glindsell** [comment]
@gaocegege splitting up this work into it's constituent parts. Tackling the first part in a separate issue here: #1762 

Will update the changes there if you would like to follow progress.

**Comment by glindsell** [comment]
Please see comment on linked issue #1762 https://github.com/SeldonIO/seldon-core/issues/1762#issuecomment-627882928

**Comment by glindsell** [comment]
#1886 has shown that changes are now required on the operator.

This new body of work is split out into its own issue here: #1887

**Comment by glindsell** [comment]
**_Update_**

**Executor** (PR [1772](https://github.com/SeldonIO/seldon-core/pull/1772))
The PR which multiplexes a single port on the Executor (1772) passes all tests and has been merged - however, it since appears that it breaks at least one notebook (metrics) as well as the samples which need to be updated to use a single port. **TODO:** Test the commit immediately before this PR to ensure that 1772 made this breaking change and that the metrics notebook was not already broken.

**Operator** (PR [1892](https://github.com/SeldonIO/seldon-core/pull/1892))
The draft PR which moves towards removing the gPRC port from the operator and pointing all back-end traffic to the new multiplex (HTTP) port on the Executor (1892) finally passed integration tests yesterday which is good - but it does not fix the metrics notebook.

**Option 1 - Fix Ambassador metrics notebook (+ samples) and include in 1.2 Release**
I am looking into this, checking that 1772 did in fact break the notebook, and also testing notebooks which use Istio to see if any changes need to be added to 1892 for Istio. If all integration tests pass and all notebooks and samples work then the changes can be included in 1.2.

**Option 2 - Revert changes for 1.2 Release**
If there are too many areas that this work touches to be fixed by the 1.2 release, the two PRs which work towards implementing the multiplexing so far (1772 & 1892) can both be merged into one and saved as a Draft PR. The one that has been merged (1772) can then be reverted to undo the incremental changes to the Executor and fix the notebooks for the 1.2 release. The new draft PR can then be worked on after the release.

**Comment by glindsell** [comment]
Option 1 completed: #1892 contains the fix for Ambassador metrics notebook (#1886) and has been merged
