### ISSUE TITLE
Create a benchmarking framework

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1731]
* Test operator under load
 * Test executor under load
 * Test model servers under load via Seldon and without to compare.

**Comment by gaocegege** [comment]
The operator itself is hard to be the bottleneck. Overhead in the control plane mainly comes from conversion webhooks. Since Seldon only has the webhook for Seldon's own resources, it is not a huge problem. The other two points are important to us (We are investigating if we could replace our own Serving CRD implementation with Seldon Core)

**Comment by cliveseldon** [comment]
@gaocegege   Happy to discuss in more detail if you want to ping me on the community slack.
