### ISSUE TITLE
Investigate test_model_template_app_grpc_metrics flakiness

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1745]
it seems that unit test `test_model_template_app_grpc_metrics` has flakiness behaviour, it would be good to understand why this is the case

**Comment by RafalSkolasinski** [comment]
Do you have example of failures I could investigate?

**Comment by axsaucedo** [comment]
@RafalSkolasinski this is the logs for the PR build that failed https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1744/1.log

**Comment by RafalSkolasinski** [comment]
Hmm... it looks it is failing on 
```
response = stub.Predict(request=request)
```
due to 
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1587913080.836870266","description":"Error received from peer ipv4:0.0.0.0:5000","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```

but that should be no different than for 
- test_model_template_app_grpc
- test_model_template_app_grpc_tags
tests so not sure why this specific test should be flaky when others are not.

Also in all cases the `start_microservice` helper checks if one can successfully connect to `5000` port.
Maybe that check is not enough for gRPC? @cliveseldon

**Comment by RafalSkolasinski** [comment]
Current assumption is that despite check in `start_microservice`
```python
        for q in range(10):
            s1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            r1 = s1.connect_ex(("127.0.0.1", 5000))
            s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            r2 = s2.connect_ex(("127.0.0.1", 6005))
            if r1 == 0 and r2 == 0:
                break
            time.sleep(5)
        else:
            raise RuntimeError("Server did not bind to 127.0.0.1:5000")
```
that one can connect to `5000` the gRPC is not ready for some obscure reason.

We may introduce usage of [wait_for_ready](https://github.com/grpc/grpc/tree/master/examples/python/wait_for_ready) in the unit tests.

/priority p3

**Comment by axsaucedo** [comment]
It seems flakiness may still be present in grpc test, as seen in 2206 - logs: https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2206/1.log

**Comment by RafalSkolasinski** [comment]
This seems to have been initially solved by introducing retry mechanism with `tenacity` package in https://github.com/SeldonIO/seldon-core/pull/1816  -  maybe this run was unlucky and exceed number of retries?

Actually, digging further, the waiting for microservice have been further improved by @agm in https://github.com/SeldonIO/seldon-core/pull/1844 where getting microservice have been moved to the fixture. 

I'm quite puzzled why the problem came back...
