### ISSUE TITLE
Allowing customised parameters when passing multipart-form-data 

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#1894]
Hi,
I noticed that passing of file input in form-data to seldon restricts the user to pass seldon set parameters like strData and binData only.

![image](https://user-images.githubusercontent.com/57779683/83257216-7c689480-a1e6-11ea-837b-0c649b3a032e.png)

Is there a way we could allow customised parameters to be passed when passing file input.
Eg: I want to pass a video file as input , I always need to use binData as the key ? Can I not pass it with key "filepath" and I handle the  base64 encoding within my predict_raw function in the Model.py file?
Expecting your reply

**Comment by cliveseldon** [comment]
I suppose the only issue is when to know when to use base64 decode and when to use UTF8 decde?
Apart from that you can have any fields if you are using predict_raw.

**Comment by divyadilip91** [comment]
Hi Clive
My current program takes an image as input. So basically i need the binary data that is the base64 encoded string Hence I am able to pass the image file as input using bindata as keyword. I also found that the else condition works for only text files like readme.md or any. .txt file that contains binary data..so passing a videofile or image file with keyword other than "binData" always throws an error since the else condition uses .decode(utf-8). Hence this is restricting the user to use keyword binData. Can there be a solution to this?

**Comment by cliveseldon** [comment]
yeah. I'm not sure what the best solution would be unless there is a standard way in form data to know whether the enclosed data in binary or utf8. @adriangonz

**Comment by adriangonz** [comment]
As @cliveseldon mentions, the blocker here is that we need to know if the content is base64-encoded or plain text / UTF8. We currently use the `binData` key as a way to let the user specify that.

@divyadilip91 could you elaborate on what's blocking you from using `binData` in your current use case?

**Comment by divyadilip91** [comment]
@adriangonz I had a similar requirement regarding passing of data using our own customized parameters as input instead of using the predefined keys defined by seldon.Reference #1792 
This issue was resolved since seldon provides methods like predict_raw that accepts the input as it is ,thus removing the constraint. 

So similarly, in my current usecase I have to pass customised keys and not predefined keys under form data.
Incase we need to create customer specific microservices using seldon and the customer requires their own input format of keyword to be passed, would it not be an issue to restrict with a mandatory key within which only, their required format of input can be passed(same with strdata and bindata}. 

Eg: I always have to upload an image or video or an audio file using the keyword binData where in I actually want to pass the file with keyword "image", "video", "audio (basically customised parameters).

**Comment by adriangonz** [comment]
When the endpoint receives uploaded files it needs to make sure that, after they are read, the content matches what it would receive regularly through JSON or a form. Therefore, even if these were custom keys, we would still need to know how to transform that data so that it's equivalent to what the endpoint would receive if this weren't a file. The problem then is how to infer which transformation we need to make with custom keys. 

In the medium to long term, we could explore reading the MIME headers for each field (these can be set separately for each file in the form). For example, `application/octet-stream` could be equivalent to `binData`. It's not 100% clear how (if) this would work though.

In the immediate term, it seems that the best option would be to either:

- Transform the payload in the client so that it's sent as custom `jsonData` fields or as `binData` (instead of sending it as files).
- Add some sort of proxy between the client and the Seldon service, which transforms the customer's upload.

**Comment by cliveseldon** [comment]
Closing. Can you reopen if V2 protocol does not help with this?
