### ISSUE TITLE
Seldon Operator automatic update from v1.1.0 to v1.2.0  causes seldondeployment failures

### ISSUE THREAD

**Issue by nakfour** [SeldonIO/seldon-core#2009]
As part of ODH we subscribe to the seldon operator using a subscription with 
```
startingCSV: seldon-operator.v1.1.0
```
and automatic updates enabled. This is on Openshift 4.x , hence OLM will download and install v1.10 before upgrading to v1.20, that leaves stale mutatingwebhooks and validatingwebhooks that have not been cleared, so when we deploy a model we get
```
oc create -f modelfull-odh-test.json
Error from server (InternalError): error when creating "modelfull-odh-test.json": Internal error occurred: failed calling webhook "v1alpha2.vseldondeployment.kb.io": Post https://seldon-webhook-service.opendatahub.svc:443/validate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Seldon")

```
This is related to ODH issue https://github.com/opendatahub-io/odh-manifests/issues/136

**Comment by cliveseldon** [comment]
The issue is that 1.1.0 created a singe webhook which did not allow namespaced installs without conflicts. 1.2.0 creates a webhook whose name is prefixed by the namespace. At present there is no way to clean up resources for cluster-wide objects on operator deletion.

The manual fix is to delete the webhook configurations created by 1.1.0 operator.
For 1.2.0 and above the webhook configurations will be updated if they exist so will work on upgrades.

We can look to create a fix that tries to delete 1.1.0 named webhooks if they exist for the next release.

**Comment by cliveseldon** [comment]
@nakfour In ODH did you tests run with a watch namespace or cluster-wide?

**Comment by cliveseldon** [comment]
For namespaced the issue would occur.
