### ISSUE TITLE
Seldon Python Server memory leak in multithreading mode

### ISSUE THREAD

**Issue by vladislavkoz** [SeldonIO/seldon-core#2422]
## Describe the bug

We've detected that the Seldon Python Server uses 100% of RAM in multithreading mode. We've created a memory dump and analyzed it. Looks like it spawns a lot of threads which takes some memory part. It should create 10 by default but looks like it creates more. The memory usage increasing slowly but after some processing, the pod is going to get OOM. 
**We've tested it with GUNICORN_THREADS variable equal to '1' but it didn't help.** 

**It is very interesting because it works well with FLASK_SINGLE_THREADED variable.** 

## To reproduce
1. The model used: BART with "pipenv run seldon-core-microservice"

-->

## Environment
seldon-core==1.2.0
Python 3.7.7

**Comment by adriangonz** [comment]
Hey @vladislavkoz ,

This should get fixed in Seldon Core `1.2.2` (i.e. for models wrapped with version `1.2.2` of the Python wrapper). 

To explain a bit more, the previous default was running with Flask's development server, which spawns a new thread for each requests and leaks some memory. Previously, the only way to enable Gunicorn was setting the number of workers to 2 or more. On `1.2.2` this was changed, so that by default we always use Gunicorn with 10 threads (as you mentioned). 

It would be great if you could try this out. Feel free to reopen if this is still an issue after upgrading!
