### ISSUE TITLE
What MLFlow model flavors are supported

### ISSUE THREAD

**Issue by Marcus-Rosti** [SeldonIO/seldon-core#2559]
I've been trying determine which mlflow flavors are supported and so far the only one that works e2e is Sci-kit learn.

The ones I've tried so far are sklearn, pytorch, tf, mllib, mleap, h2o. Only sklearn has worked e2e so far. I'm curious if there's clarification on which ones are truly supported by the mlflow server outside of a theoretical sense.

## Notes
1. sklearn worked entirely as expected
2. pytorch/tf had issues around datatypes on both predict and response meaning the call 500'ed
3. h2o with sparkling water won't save files in the correct spot
4. mleap requires a java runtime
5. mllib requires a spark cluster

NB. totally understand that these two projects don't necessarily interoperate and I'm willing to make PRs or get them to work but just want so clarification for LOE

**Comment by adriangonz** [comment]
Hey @Marcus-Rosti , the `MLFLOW_SERVER` runtime only supports the `python_function` backend at the moment. You can find a few more details here: https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#pre-requisites

We decided to go for that one initially because it's pretty generic and allows to give out-of-the-box support for a bunch other backends. Are there any backends which are not able to export to `python_function`?

**Comment by Marcus-Rosti** [comment]
@adriangonz I'll compile a list today

**Comment by axsaucedo** [comment]
@Marcus-Rosti just following up, do you have any updates on this?

**Comment by cliveseldon** [comment]
Closing. Please see [MLServer](https://github.com/SeldonIO/mlserver) docs.
