### ISSUE TITLE
Java Language Wrapper Vulnerabilities

### ISSUE THREAD

**Issue by indranilr** [SeldonIO/seldon-core#2754]
Java wrapper 0.3 version is impacted by [https://nvd.nist.gov/vuln/detail/CVE-2020-5421](url) due to use of Spring boot 2.2.4 release which is picked by vulnerability scanners. Please upgrade to 2.2.10 or higher , 2.3.4 or higher.

Another vulnerability exists due to use of HttpClient  4.5.10 [https://nvd.nist.gov/vuln/detail/CVE-2020-13956](url). Please upgrade to Httpclient 4.5.13 or higher.

**Comment by adriangonz** [comment]
Hey @indranilr, 

We are exploring replacing the Java wrapper for the new JNI one which leverages the existing Python inference server and communicates with a JVM using JNI. You can find more details on the [JNI wrapper on the docs](https://docs.seldon.io/projects/seldon-core/en/latest/java-jni/README.html). This means that all the networking is handled by the Python package, which is better maintained than the Java one (while still letting you define your inference logic in Java).

Because of that, the JNI wrapper doesn't use Spring at all. However, it still uses the same `io.seldon.wrapper:seldon-core-wrapper` Java package under the hood (which includes Spring).

Based on the above, the best resolution for this issue is probably to consider moving to the JNI wrapper and removing Spring (and all the other unused deps) from the `io.seldon.wrapper:seldon-core-wrapper`.  I've opened a separate issue for this here: https://github.com/SeldonIO/seldon-core/issues/2759 .

**Comment by satyakisen** [comment]
Hi @adriangonz 
Based on your above comment, can you please suggest a working example on how to use the java-jni wrapper excluding spring framework from the `io.seldon.wrapper:seldon-core-wrapper`.

**Comment by adriangonz** [comment]
Hey @satyakisen, this issue hasn't been prioritised yet on our roadmap. However, it should be possible to create a "slim" S2I template that doesn't have Spring (i.e. with a custom `pom.xml`).

**Comment by adriangonz** [comment]
Closing as this will be part of MLServer's roadmap.
