### ISSUE TITLE
Elasticsearch stored feedback message is undeterministic when sent to a canary deployment

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2823]
Currently when sending a feedback message to a model with a canary, would result in undeterministic results as follows:
* Predict request is sent to `REQUEST_ID` which goes through PREDICTOR_A
* Request logger stores the request data in the PREDICTOR_A elastic index
* Feedback message for A is sent and incorrectly goes to PREDICTOR_B
* Request logger stores the request data in the PREDICTOR_B elastic index

This results in request data stored in one index whislt feedback stored in the other.

The solutions that have been explored so far include:
1. Extend request logger to check all indexes for request ID and then insert feedback to existing one
2. Update the index to not have a suffix with PREDITOR_ID

**Comment by ryandawsonuk** [comment]
My preferred option at the moment is 2. An earlier version of the logger did a lookup rather than an upsert and it significantly reduced the maximum throughput before hitting elastic max connection limits. Option 2 presents a problem for shadows for them you get two responses (effectively two requests) distinguished only by the predictor. This could be handled by putting the shadow response in the same document as the main response but in a different section.

**Comment by cliveseldon** [comment]
MAB behaviour would be hard to solve without doing istio traffic routing updates even at Envoy level?

**Comment by cliveseldon** [comment]
If run via Iter8 and two separate sdeps this should not be an issue.
