### ISSUE TITLE
Executor does not send feedback to Routers.

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#2827]
https://github.com/SeldonIO/seldon-core/blob/master/executor/predictor/predictor_process.go#L135

**Comment by axsaucedo** [comment]
In this case it would skip calling the ROUTER component in favour of getting it from the meta (https://github.com/SeldonIO/seldon-core/blob/23d7dc5a0cf50d3aa642b25161d7e7176b6b9816/executor/predictor/predictor_process.go#L247), and then it would just call the MODEL components via `send_feedback` instead of `predict`, so it should still pass the feedback to the router MODEL nodes.

Do you mean that currently it's not passing the data to the `MODEL` components?

**Comment by cliveseldon** [comment]
For MABs there is logic in send-feedback to update state so I think it should send feedback to routers.

**Comment by axsaucedo** [comment]
Oh I see what you mean, so basically it shouldn't call the "route" method, but it should still call the send_feedback method. Ok I can see that the MAB router also has a send_feedback logic, so it would make sense. It seems that also adding the `v1.SEND_FEEDBACK` method in:
https://github.com/SeldonIO/seldon-core/blob/23d7dc5a0cf50d3aa642b25161d7e7176b6b9816/executor/predictor/predictor_process.go#L139

It seems that the predictor bean also has similar logic:
https://github.com/SeldonIO/seldon-core/blob/23d7dc5a0cf50d3aa642b25161d7e7176b6b9816/engine/src/main/java/io/seldon/engine/predictors/PredictiveUnitBean.java#L300

I'm not as familiar with the java side, so just to confirm, is this assumption correct?

I do agree that it would make sense to also ensure the send_feedback is passed to the router element, as it could help update its current state. Do you think it should be done explicitly by providing the `method` in the CRD, or by default?

**Comment by cliveseldon** [comment]
Yes. That makes sense. The logic is in the engine but missing from the executor.
