### ISSUE TITLE
Helm Chart improvements: labels and annotations for service and deployment

### ISSUE THREAD

**Issue by pierluigilenoci** [SeldonIO/seldon-core#2860]
It would be very helpful to have the ability to define `labels` and `annotations` for the `seldon-webhook-service` (https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/service_seldon-webhook-service.yaml#L4-L9) and pods via `seldon-controller-manager` deployment (https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L23-L31)

For example, a possible use is to configure Prometheus endpoints to prevent it from trying to scrap the wrong endpoints.

<img width="1206" alt="Screenshot 2021-01-21 at 12 25 17" src="https://user-images.githubusercontent.com/36044817/105344911-dd186780-5be3-11eb-955f-ece2d1b029dd.png">
<img width="1572" alt="Screenshot 2021-01-21 at 12 26 03" src="https://user-images.githubusercontent.com/36044817/105344919-df7ac180-5be3-11eb-8f50-bb1b6168e9ca.png">

Note: for the deployment make sense to have on both side: `metadata.annotations` and `spec.template.metadata.annotations`, `metadata.labels` and `spec.template.metadata.labels`.

**Comment by cliveseldon** [comment]
Can you explain your use case for annotations for webhook svc a bit more?
Is it mainly adding further annotations to the main SVC?

**Comment by pierluigilenoci** [comment]
Annotations are used for multiple reasons: node taints, service accounts, secrets handling, Prometheus scraping, monitoring, logging, alerting, network policies, billing, etc.

A generic way to add annotations is the better choice.

Examples:
1) From Prometheus chart.
deployment annotations:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L265
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/deploy.yaml#L8
pod annotations:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L234
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/deploy.yaml#L28

2) From Grafana chart
deployment annotations:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L20
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/deployment.yaml#L12-L14
pod annotations:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L109
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/deployment.yaml#L43-L45

**Comment by pierluigilenoci** [comment]
To solve the errors in the image above you must add the annotation `prometheus.io/port: '8080'` [here](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L23-L25)

**Comment by adriangonz** [comment]
Hey @pierluigilenoci, I see the point on adding annotations / labels to the operator pod. The webhook may be a bit trickier though, since it can also get created dynamically by the operator (required for certain environments). I'd also argue that the webhook is a very internal piece owned by the operator, so it may not be required to expose control through the chart?

It would be good to hear your thoughts on the webhook piece @pierluigilenoci. It'd also be good to learn why is Prometheus trying to scrap the webhook service?

In the meantime, would you be keen to contribute a PR to add annotations and labels to the operator deployment?

**Comment by pierluigilenoci** [comment]
@adriangonz @axsaucedo any news?

**Comment by pierluigilenoci** [comment]
@adriangonz @axsaucedo any news?

**Comment by pierluigilenoci** [comment]
@adriangonz @axsaucedo any news?

**Comment by adriangonz** [comment]
Hey @pierluigilenoci , could you provide more details over what setup causes Prometheus to scrap the webhook endpoints? 

Conscious that there are multiple official ways to install Prom at the moment (e.g. with their operator, their "vanilla" chart, etc.), so it would be useful to understand a bit more about this so that we can prioritise the issue accordingly.

**Comment by adriangonz** [comment]
Right, I was under the impression that the default setup of Prometheus would cause issues with the default installation of Seldon Core.

If this is more about configuring the ports / webhooks, I'd say that it's more of an internal detail and therefore not as high priority. There're quite a few other things with a higher urgency at the moment, so unless someone else from the community wants to pick it up, I'm afraid that we won't be able to prioritise it in the near / mid term. 

In the meantime, happy to keep this issue in the backlog for a while, in case someone wants to volunteer (or we've got any spare time to work on this one).

**Comment by pierluigilenoci** [comment]
@adriangonz the default configuration actually creates a problem.

By adding this annotation
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L27
Prometheus scrapes all ports open.
In the default configuration, the open ports are this
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L140
(so https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/values.yaml#L105)
and this
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L143 

Port `8080` responds correctly, port `4443` returns `400` and Prometheus reports it as a broken entry-point.

**Comment by adriangonz** [comment]
@pierluigilenoci right, could you share how was Prometheus installed / configured? As far as I'm aware, we haven't seen this before with Prom, so it would be to learn whether this occurs with a default install of Prometheus, or is due to some extra config.

**Comment by pierluigilenoci** [comment]
@adriangonz default values of official helm chart.
Specifically https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1678

**Comment by adriangonz** [comment]
Oh right, I see your point now. 

The Prometheus config for Seldon Core must include this extra target rule, which ensures that  multiple ports can be scraped from the same pod. Since inference graphs expose multiple metrics ports (i.e. one per each step of the graph), this is required for Seldon Core to ensure we can collect metrics for all the different models within the graph.

```yaml
- source_labels: [__meta_kubernetes_pod_container_port_name]
  action: keep
  regex: metrics(-.*)?
```

At the same time, since the rule above essentially means that Prom will look for ports named `metrics`, this also ensures that only the relevant port of the operator pod get scrapped. 

For more info on how to configure Prom to work with Seldon Core, you can also check this page of the docs:

https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html#metrics-endpoints

**Comment by pierluigilenoci** [comment]
I will try to do as suggested even though I don't like it very much. 
For me, forcing the global configuration of Prometheus just to make Seldon work is a shortsighted approach. 
A tool should be as autonomous as possible in its configuration, minimizing the impact on the ecosystem in which it is integrated.
Obviously, this is just my opinion.

**Comment by adriangonz** [comment]
Don't let perfect get in the way of good.

I agree that minimising the required Prom config would make SC easier to use. However, as discussed above, the impact of that would go beyond just tweaking the operator's labels and annotations and would need to account for aggregating the metrics coming from multiple nodes of an inference graph. At the time, we couldn't identify a different (and "elegant") way to ask Prom to target multiple ports within the same `SeldonDeployment` pod. Therefore, this would be more of a longer-term issue. 

If you're up for it, it would be great to hear your thoughts on how the current design could be improved. Although, since that would be out of the scope of the current issue, it would be best to continue the discussion on a new one.

**Comment by pierluigilenoci** [comment]
I did not understand why you closed the ticket because in any case the annotations/labels are still a missing feature (which would also partially buffer the problem of Prometheus).

That said, a possible solution to your problem would be to move the scraping from the pod itself to the services.
I mean to create a service for each port that needs to be scraped by Prometheus. 

To be more elegant you can use ServiceMonitor (ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#related-resources)

**Comment by adriangonz** [comment]
Hey @pierluigilenoci,

As discussed above, the solution proposed in this issue wouldn't the cover the whole scope of the problem that it tries to solve (i.e. making sure Prom only scrapes the right ports), which would also require thinking about the metrics ports in `SeldonDeployment` resources. At the moment, this should be unblocked by the [workaround described in the docs](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html#metrics-endpoints). 

Having said so, I do agree that it would be worth continuing the discussion on how to improve this approach. In particular, I think that it could be interesting to explore the service-level approach you've suggested above. Since that would be out of the scope of this issue, I've opened up a [new one](https://github.com/SeldonIO/seldon-core/issues/3895) where we can keep the discussion going. I've added some background context there, but please feel free to add anything else if I've missed something.

Regarding the use of `ServiceMonitors`, we're already exploring the use of the Prometheus operator in https://github.com/SeldonIO/seldon-core/issues/1502 . I'm not directly involved with that though, so maybe would be worth reaching out on that thread for more details?

**Comment by pierluigilenoci** [comment]
I am pleased to have directed you towards a solution.

However, I continue to argue that giving the ability to add `labels` and `annotations` to all the manifest in the chart is a good thing. 😛
