### ISSUE TITLE
Error importing BaseRespnse from werkzeug.wrappers due breaking Flask update

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#4017]
## Describe the bug

As it has been reported in https://github.com/SeldonIO/seldon-core/issues/4014 we have found that the base python wrapper when built from scratch will fail with the error below. This is because of a 2nd-level+ dependency from Flask where werkzeug removed/moved the BaseResponse class resulting in this breaking. The solution is to pin werkzeug to version 2.0.3 in the base image, and rebuild all relevant images from there.

```
from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/__init__.py)
```

## Workaround

The workaround is relatively simple, and just requires users to pin `werkzeug==2.0.3` in the respective requirements.txt.

## To reproduce

This can be reproduced by rebuilding an image with the existing dependencies as this is broken on the version of Flask until they pin/update it.

**Comment by saeid93** [comment]
I'm still facing the same issue despite the update in line 40-41 in the [setup.py](https://github.com/SeldonIO/seldon-core/blob/0ba7b94c4637658aad3d3f9db2892e43d86a08de/python/setup.py) for addressing this issue Seldon still installs with the Werkzeug-2.1.2 in the installation and it should be removed and replaced with Werkzeug-2.0.2 in order to work.

**Comment by RafalSkolasinski** [comment]
@saeid93 if the issue is not solved for you, could you please open a new issue describing a steps to reproduce?
This should now be fixed on master and we do not see any related problems in our test suite.
