### ISSUE TITLE
Python Wrappers Version 2

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#406]
We should update the Python wrapper to add more streamlined code paths.

 * For REST requests always parse into proto buffers and have a central shared processing step that is general to gRPC and REST and works on the proto buffers.
 * Convert the various components - models, transformers, routers etc to use a single code base as there is a lot of shared code.

This work could be Python 3 specific and add in some of the tasks such as #392

**Comment by jklaise** [comment]
Closely related we should have a think about function signatures for components written in Python. It makes sense to keep these clean and data-science focused (e.g. predict should take features X directly rather than the full SeldonMessage request) at the cost of us doing the SeldonMessage parsing when they enter and exit the component, but the user might want more flexibility (e.g. #407 where they might want access to the SeldonMessage metadata from within the component).
