### ISSUE TITLE
No module _distutils_hack when starting seldonio/seldon-core-s2i-python3:1.14.0

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#4209]
```
docker run -it --rm seldonio/seldon-core-s2i-python3:1.14.0 bash
Error processing line 1 of /opt/conda/lib/python3.8/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
(base) [root@e5903679198a microservice]# 
```

**Comment by cliveseldon** [comment]
Some discussion related https://github.com/pypa/setuptools/issues/2980

**Comment by cliveseldon** [comment]
```
pip install setuptools==63.1.0
```
fixed the error when run inside the container..

**Comment by axsaucedo** [comment]
As per the conversation on [the community slack](https://seldondev.slack.com/archives/C03DQFTFXMX/p1657173722142809?thread_ts=1657150946.069979&cid=C03DQFTFXMX), we had a quick look just now and we have seemed to validate the error appears on the base image, but when tesing across other images it seems it may not affect the running of seldon core containers - have you seen behaviour that shows otherwise? If so it would be great if you could  share with us a manifest that we could use to reproduce
