### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess when loading model in Gunicorn

### ISSUE THREAD

**Issue by rlleshi** [SeldonIO/seldon-core#4429]
According to the [docs](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html?#gunicorn-and-load) we should use the `load()` method to load and initialize the model. However, when passing the model to the desired Cuda device with torch `model.to(device)` the following error is thrown:

```
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method.
```

This is different from this existing [issue](https://github.com/SeldonIO/seldon-core/issues/2680) where the problem was that the `load()` method was not being used. Also, the specific suggestions at this torch [issue](https://github.com/pytorch/pytorch/issues/40403) do not work in this context.

**Comment by RafalSkolasinski** [comment]
@rlleshi please provide a complete example that reproduces the issue that we could run on our end

**Comment by rlleshi** [comment]
hi @RafalSkolasinski thanks for reaching out. I am attaching a zip file that can reproduce this
[cuda_error.zip](https://github.com/SeldonIO/seldon-core/files/9991606/cuda_error.zip)

The contents are:
- `Detection.py`  - seldon python wrapper
- `Dockerfile` - the dockerfile for the environment
- `download_model.sh` - script to download the detection model
- `faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person.py` - model config file

First, create the image: `nvidia-docker build -f Dockerfile . -t seldontest`
Then run the container: `nvidia-docker run -p 5000:5000 -p 9000:9000 --name seldontest -it seldontest`

You'll get the error.

**Comment by rlleshi** [comment]
@RafalSkolasinski kind ping. Did you have a chance to check it out?

**Comment by RafalSkolasinski** [comment]
Hey @rlleshi, thanks for the example, unfortunately I did not yet manage to have a look

**Comment by RafalSkolasinski** [comment]
Hey @rlleshi, wonder if you tried getting it up and running with our V2 runtime, MLServer ([GitHub](https://github.com/SeldonIO/MLServer/) & [docs](https://mlserver.readthedocs.io/en/latest/)). We are going to move to V2 protocol as a default new standard and the runtime we are going to be mostly focused on. We have a HuggingFace [example](https://mlserver.readthedocs.io/en/latest/examples/huggingface/README.html#gpu-acceleration) that talks about GPU acceleration.

**Comment by rlleshi** [comment]
I could give it a try. But did you try to check the minimal example here once?

**Comment by cliveseldon** [comment]
Looks like this is related to [this](https://github.com/pytorch/pytorch/issues/40403). Are you running pytorch?

**Comment by rlleshi** [comment]
@cliveseldon thanks for your response. 
Yep, I am aware of that and also mentioned above in the issue that the suggestions there don't really work in this context.

**Comment by adriangonz** [comment]
Hey @rlleshi ,

It looks like this is due to how the V1 wrapper spins up its worker processes, i.e. using `fork` (instead of `spawn`). When forking a process, some memory regions get copied down from the parent to the worker, and it seems that includes some CUDA bits?

Note that the aim of the `load()` method is to offer a middle ground between `fork` and `spawn`, as it's only called on the worker processes. Therefore, it's unclear why it's still complaining in this case.

Changing the semantics from `fork` to `spawn` would be quite a big breaking change for the V1 wrapper (`fork`'s behaviour is still desired - and expected - in some cases). However, our "V2 wrapper" (i.e. [MLServer](https://mlserver.readthedocs.io/)) uses `spawn` as a default.

Therefore, as next steps, I think it would be interesting to:

- As an experiment, move the `mmdet` import within your `load()` method (i.e. as an inline import). That's the only bit I can see which gets executed outside of the workers (besides `__init__`, but that one looks harmless). 
- Migrate your model to a [MLServer customer runtime](https://mlserver.readthedocs.io/en/latest/user-guide/custom.html). Since MLServer uses `spawn`, if it works, that would validate the fork vs spawn issues - and would provide a way forward towards resolution.

**Comment by rlleshi** [comment]
@adriangonz ty for sorting this out.

I am closing the issue since you addressed the root problem for V1. FYI: adding the import to `load()` didn't make a difference.

Migrating to V2 solves the problem as expected.
