### ISSUE TITLE
The max message size for kafka is set only on pipeline topics and not on the respective model topics

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#4668]
## Describe the bug
In Kubernetes Deployment, we are able to specify the "message.max.bytes" property for Kafka topics created by seldon-core-v2. It seems, that this property is only set on the topics for the pipelines, but not for the models, yielding inconsistencies. If one of the models produces a message >1MB (our current broker default) the request gets stuck without any error indicating, what's happening.

## To reproduce

1. Create models
2. Create a pipeline
3. Examine the created Kafka topics. The Pipeline topics contains the "message.max.bytes" property, the model ones doesn't

## Expected behaviour
I'd expect the property to be consistently set for all topics created by Kafka.

## Environment

* Cloud Provider: AWS (EKS + MSK)
* Kubernetes Cluster Version: 1.24
* Deployed Seldon System Images: all images for seldon core v2.2.0

**Comment by cliveseldon** [comment]
maybe due to 

- a change in the way [we create the adminClient in the model gateway](https://github.com/SeldonIO/seldon-core/blob/cba1c07420e6fb28f2a62986d181d700bd249ff4/scheduler/pkg/kafka/gateway/infer.go#L148-L160) which is not passed `message.max.bytes` from kafka config and it is this client that creates topics of they don;t exist
- Also I see we don't set `fetch.max.bytes` by default which I think also should be set for consumer. This could be added by users to the kafka config but as we default to a large bytes for `message.max.bytes` we should also set this by default to same value.

**Comment by cliveseldon** [comment]
Closed by #4675. @SDJustus if you could validate your end.
