### ISSUE TITLE
exec /executor: argument list too long

### ISSUE THREAD

**Issue by JSilent** [SeldonIO/seldon-core#4973]
## Describe the bug

With complex inference graph, a log pops up in the container and the Pod becomes CrashLoopBackOff:
exec /executor: argument list too long

## To reproduce

1. Install seldon model with kubectl/helm

## Expected behaviour

The Pod becomes running.

## Environment

Cloud Provider: AWS EKS
Kubernetes Cluster Version: v1.21.14
Deployed Seldon System Images: docker.io/seldonio/seldon-core-operator:1.15.0

[seldon-deployment.yaml.txt](https://github.com/SeldonIO/seldon-core/files/11949817/seldon-deployment.yaml.txt)

**Comment by RafalSkolasinski** [comment]
Hi, did you consider using Core v2? Given your use case you may benefit a lot from multi-model serving and the issue should not be present there.

**Comment by JSilent** [comment]
> Hi, did you consider using Core v2? Given your use case you may benefit a lot from multi-model serving and the issue should not be present there.

Not yet. Can the existing seldon deployment yaml file be re-used in Core v2?

**Comment by agrski** [comment]
> Not yet. Can the existing seldon deployment yaml file be re-used in Core v2?

The format of a `Pipeline` in Core v2 isn't the same, but you will probably find it easier to read and write, as it doesn't use the deeply nested tree structure of a Core v1 `SeldonDeployment`

**Comment by agrski** [comment]
I'll also add that this isn't a bug with Seldon Core.  `argument list too long` means whatever shell or `exec` tool is reading the arguments for a process is unable to do so because it has hit a limit.  That limit is handled by Kubernetes or the OS running on your Kubernetes nodes, so there's nothing we could do to fix that.

**Comment by JSilent** [comment]
> I'll also add that this isn't a bug with Seldon Core. `argument list too long` means whatever shell or `exec` tool is reading the arguments for a process is unable to do so because it has hit a limit. That limit is handled by Kubernetes or the OS running on your Kubernetes nodes, so there's nothing we could do to fix that.

Is there any workaround to overcome the limit? Assuming no permission to change the limit of the host OS.

**Comment by JSilent** [comment]
Is it possible to change the dockerfile to enlarge the limit of guest OS when building the executor?

**Comment by agrski** [comment]
> Does Core v2 support container image deployment?

Core v2 is sightly different from Core v1.  In Core v1, you had to build a container for each model.  In Core v2, you create a `Server`, which can use a custom image, and `Models` can then be scheduled onto that server.  You could see if a custom server based off MLServer would fit your needs.

> If no, shall we run v1 and v2 in parallel in the same cluster?

Yes, Core v1 and Core v2 can be run in the same cluster, but should not be _installed_ in the same namespace because the name of the operator pod is the same in both.

> Is it possible to change the dockerfile to enlarge the limit of guest OS when building the executor?

You could try this and let us know if it does work!

**Comment by JSilent** [comment]
Thanks for the advise.

> > Is it possible to change the dockerfile to enlarge the limit of guest OS when building the executor?
> 
> You could try this and let us know if it does work!

I tried to enlarge the limit and re-build the executor but failed.

I will try Core v2 for this.
