### ISSUE TITLE
helm-charts upgrade fails on ambassador

### ISSUE THREAD

**Issue by OrBarda** [SeldonIO/seldon-core#543]
When trying to upgrade the helm charts of Seldon-core to release 0.2.7, it shows a problem in the deployment which is related to the ambassador:
![image (5)](https://user-images.githubusercontent.com/15226665/57277904-ca779b00-70ad-11e9-9272-3b337a1bfaa3.png)
Then when trying again to upgrade getting the following:
![image (6)](https://user-images.githubusercontent.com/15226665/57277965-f266fe80-70ad-11e9-9ea4-26a76194248d.png)
And eventually what happens is that a new cluster-manager is up but the old one stay as well and for upgrading the ambassador a delete of the chart is needed which causes a problem in availability.

**Comment by ryandawsonuk** [comment]
I think this is because we're now using the ambassador helm chart. https://github.com/helm/helm/issues/1193 has been a helm issue for a while - an example of a similar failure with a chart resource (also a service account but can happen with other resources too) is https://github.com/jetstack/cert-manager/issues/677 The issue is reported as fixed but the fix is quite recent. Which helm version are you using?

**Comment by OrBarda** [comment]
we are using 2.12.3.

**Comment by ryandawsonuk** [comment]
I think the next step is to see if we can recreate this with the latest version of helm. We can install an old version of seldon-core and then do a helm upgrade to the new version. I'll aim to do this soon.

**Comment by ryandawsonuk** [comment]
Actually ambassador will [soon be removed from the seldon-core main chart](https://github.com/SeldonIO/seldon-core/pull/559) so anyone upgrading to that version will need to install ambassador separately or add it to their own wrapper chart. This issue will then no longer apply

**Comment by cliveseldon** [comment]
Fix by new separation of operator from ingress.
