### ISSUE TITLE
How can I modify the logging format of REST API for StackDriver and BigQuery?

### ISSUE THREAD

**Issue by yu-iskw** [SeldonIO/seldon-core#557]
## Motivation
I would like to collect logs of RESTful APIs with seldon in StackDriver and store logs to BigQeury from Stackdriver. In order to query logs on BigQuery, the logging format have to be JSON.

## Question
How can we custom the logging format of seldon applications to fit to StackDriver and BigQuery?

**Comment by cliveseldon** [comment]
The response from HTTP requests in in JSON format so you could add logging at that point. 
For a more integrated solution we are looking at adding request logging connectors to Seldon so would be interested in your detailed requirements in this area.

**Comment by yu-iskw** [comment]
Thank you for the comment. It means, we can collect the logs to stackdriver by adding logs in model, as long as we define the format for seldon, right?

**Comment by cliveseldon** [comment]
I think the ideal solution would be a general payload logging solution probably sent from the service orchestrator. You are free to extend your models to add StackDriver logs in each component.

**Comment by ryandawsonuk** [comment]
We're addressing this through https://github.com/SeldonIO/seldon-core/pull/616

The initial integration is EFK but fluentd can be used to send to different backends and the request-logger piece in the example is pluggable so can be used to send to a backend directly (fluentd so fluentd is optional).

Alternatively you can log directly in your model implementation. Using a pluggable logger would have the advantage of being async, so as to minimise the impact on the time of your main request flow. But if that's not a concern you could certainly do it in the model. If doing it in the model you might want to use the predict_raw method instead of predict, so as to get access to the full SeldonMessage.

**Comment by axsaucedo** [comment]
@ryandawsonuk now #616 is merged can we close this?

**Comment by yu-iskw** [comment]
Why not! Thank you.
