### ISSUE TITLE
Shadow deployment for Istio

### ISSUE THREAD

**Issue by amoldavsky** [SeldonIO/seldon-core#741]
Among the various Istio examples there no example of a Shadow deployment and Istio. There seem to be no annotation support to do a shadow deployment with Istio like there is with Ambassador.

**Comment by ryandawsonuk** [comment]
Notes on this...

[ISTIO](https://istio.io/docs/tasks/traffic-management/mirroring/#mirroring-traffic-to-v2)

Two Deployments with different labels. One VirtualService pointing to one k8s Service (which matches both Deployments).

Shadow by adding a 'mirror' entry to the VirtualService.

[AMBASSADOR](https://www.getambassador.io/reference/shadowing/)

Two Deployments and two Services.

Two Mappings with same 'prefix'. Shadow by adding 'shadow: true'.

SELDON

Currently [ambassador shadowing](https://docs.seldon.io/projects/seldon-core/en/latest/examples/ambassador_shadow.html) is done by creating a second SeldonDeployment and annotating it as a shadow of the first.

For istio we can't use two SeldonDeployments as then it won't be clear which owns the single VirtualService or Service.

Instead we could have two predictors in a SeldonDeployment and mark one as shadowing the other. A field could be added to the CRD to indicate a shadow. Much as we have a 'traffic' with a numeric value to indicate a [canary traffic-split](https://docs.seldon.io/projects/seldon-core/en/latest/examples/istio_canary.html), we could have 'shadow' attribute ('true' or 'false').

Currently the Seldon operator creates a k8s Service for each predictor. For istio shadowing we would have to skip Service creation for the shadow predictor.

This would mean that the ambassador and istio shadowing would be set differently by the user. Possibly we provide a way for the istio style with predictors to also work for ambassador. (But not the other way around because the single VirtualService has to belong to a single SeldonDeployment.)

If there were canary or A/B test traffic splitting in place then there would be multiple predictors with their own weights. In the VirtualService these predictors are different destinations under the same route. There would be a [single 'mirror' for the whole route](https://istio.io/docs/tasks/traffic-management/mirroring/#mirroring-traffic-to-v2), not per-destination. So there would be a single shadow for the whole SeldonDeployment, even if an A/B test or canary is active. When weights are used we check that the weights are present and add up to 100 - we may need to exempt the shadow predictor from that check.

**Comment by ryandawsonuk** [comment]
The istio example referenced above matches to the mirror by label and the mirror shares the same k8s Service as the main version. This doesn't seem to be strictly necessary. The mirror can have its own Service and the traffic can be sent to that host. This is [what we do for traffic splitting](https://istio.io/docs/tasks/traffic-management/traffic-shifting/). Don't see an explicit example doing mirroring this way but the approach is working in the referenced PR.
