### ISSUE TITLE
Writing the predict function around pandas dataframes

### ISSUE THREAD

**Issue by PrathamSolanki** [SeldonIO/seldon-core#746]
Hi all,

I'm curious whether I can write my predict function that takes a pandas dataframe as input and also returns a dataframe.

I'm trying incorporate my preprocess step into the seldon graph for which I have a predict function that takes in a dataframe, does the preprocessing on it and returns the new dataframe:

```
def predict(train):
    # do modifications to the train dataframe
    return train
```

Is this possible with the latest version of Seldon Core?

**Comment by axsaucedo** [comment]
Hey @PrathamSolanki, at this point the only supported inputs/outpus for the wrapper are string, bytes, json or numpy array https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html. If you would like to pass a Pandas Dataframe I would advise you to serialise it (with something like Dill or Pickle) and send it using the bytes, which would look something like:
```
    def predict(self, X_bytes, feature_names=[]):
        X = pickle.loads(X_bytes)
```
The reason why we have restricted to those input types is because that allows us to expose an API that is not restricted to only Python - if we were to expect something like pandas, you would only be able to call the API with Python, which would restrict if you would like to expose that API to other non-python services (or even different libraries). 

Also be aware that if you use pickle you will also have to be aware of different versions - if you pickle a pandas dataframe and unpickle it with a different version it may fail - again, this is why we recommend to take this into consideration. Hope this helps.
