### ISSUE TITLE
Seldon container engine has not resource limit

### ISSUE THREAD

**Issue by OrBarda** [SeldonIO/seldon-core#769]
Hi, the seldon-container-engine sidecar has no resource limit, thus it takes the limit from the env, which is way too much. can you please add resource limits and requests to the charts?

**Comment by ryandawsonuk** [comment]
We have an open docs issue to make this clearer - https://github.com/SeldonIO/seldon-core/issues/761 as the question has been coming up - https://github.com/SeldonIO/seldon-core/issues/753#issuecomment-518769777

But we do have some charts with a resources section:
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-single-model/values.yaml#L23
Which gets set in the manifest:
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-single-model/templates/model.json#L24

You could set resource limits using that chart by a --set parameter or a custom values file.

Or do you mean that you want a limit set for every deployment instead of setting it for each deployment individually?

**Comment by OrBarda** [comment]
That's exactly what I meant. It will be nice not to deal with it in every deployment.

**Comment by cliveseldon** [comment]
This is application specific. Will close for now.
