### ISSUE TITLE
can we expose health check api in internal python service similar to what we have in external like /ping

### ISSUE THREAD

**Issue by klalit** [SeldonIO/seldon-core#770]

**Comment by cliveseldon** [comment]
This would need a proposal to add a user provided or Python wrapper specific `/ping` endpoint and a convention for the engine to know to use this rather than the default TCP connect check to the exposed port. We need to bear in mind the engine needs to use this default readiness check as components can be built using any custom or supported way to create a container so at present we don't enforce a convention that all components must support a `/ping` or `/ready` endpoint. We could decide to do this but might be a post 1.0 decision?

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
This is available now in 1.1.0
