### ISSUE TITLE
Tensor wrapped Numpy is read-only

### ISSUE THREAD

**Issue by lennon310** [SeldonIO/seldon-core#807]
My model class is 
```
class HHMlflowModel:
    def predict(
        self, model_input: np.ndarray, features_names: list
    ) -> np.ndarray:  
        print(model_input.flags)
```

and by sending a request with seldon client,
```
def predict_localhost() -> None:
    sc = SeldonClient()
    sc.microservice(
        method="predict",
        payload_type="ndarray",
        data=nparray,
        names=names,
        transport=REST,
    )


if __name__ == "__main__":
    predict_localhost()
```
I can see the permission of the Numpy is,
```
C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

However, if I'm sending a tensor payload type (by changing to `payload_type="tensor"`), the output will be
```
C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
``` 

so the Numpy array in the model is immutable, and I'm not allowed to `setflags` on the array either.  I saw from the source code it just extract the tensor field and recreate a new Numpy array. Why could this happen?  Is it an expected behavior?

**Comment by cliveseldon** [comment]
@axsaucedo @lennon310  can you check this with latest python wrapper

**Comment by adriangonz** [comment]
When the microservice receives the input as `tensor`, it transforms it into a `numpy` array using `np.frombuffer(...)`. The buffer we pass to `np.frombuffer(...)` is created by serialising the protobuf's `tensor` bytes into a string. This is done in the `grpc_datadef_to_array` method, which can be seen below.

https://github.com/SeldonIO/seldon-core/blob/16755fd003889de00c5426d78d2592dfe341b581/python/seldon_core/utils.py#L162-L173

The problem is that strings in python are immutable, therefore the buffer we create with `memoryview(...)` (in line 679 above) will be immutable as well. This is also highlighted in this [SO answer](https://stackoverflow.com/a/22237279). As a consequence, the `numpy` array will point to a region of memory which is read-only (since it's a string) and thus won't be writeable.

That explains why the `WRITEABLE` flag is set to `False`, but I'm not sure what is the best way forward. It could be a good idea to make it mutable for consistency with other data types. One option would be to use `np.fromstring()` instead of `np.frombuffer()`. This method makes a copy of the passed string, and thus the resulting array is mutable. I am not sure if this could have any effect on speed though...

**Comment by cliveseldon** [comment]
This way of derserializing was done for speed. I'm inclined to leave it to the user to make a copy if they want to modify the request payload. 

@lennon310 Do you have an opinion?

**Comment by cliveseldon** [comment]
Please reopen if still an issue
