### ISSUE TITLE
support ambassador_id to allow multi-tenancy 

### ISSUE THREAD

**Issue by phsiao** [SeldonIO/seldon-core#810]
See https://github.com/datawire/ambassador/blob/master/docs/reference/running.md for how ambassador_id is used to allow multiple ambassador instances in the same cluster.

Happy to help with the implementation if we can decide what is the best way to support it.  This requires both the ambassador and seldon-operator to be in sync, so the implementation needs to be very clear on what the implications are.  The straightforward implementation would be to add a `seldon.io/ambassador-instance-id` (or simply `seldon.io/ambassador-id` supported annotation, and pass the value to the service object definition.

**Comment by cliveseldon** [comment]
Yes I think a simple annotation on the deployment makes initial sense for https://github.com/datawire/ambassador/blob/master/docs/reference/running.md#ambassador_id

We still haven't got the finished story for namespaced-seldon operator so that sort of tied integration to a namespaced Ambassador could be left to a further PR later.

**Comment by phsiao** [comment]
The annotation support is added and documentation added.  Closing.
