### ISSUE TITLE
MLFLOW_SERVER ModuleNotFoundError

### ISSUE THREAD

**Issue by lennon310** [SeldonIO/seldon-core#828]
I upload the Mlflow model artifact and use MLFLOW_SERVER to run the model.
The deployment file looks like

```
graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: s3://mlflow-server
      envSecretRefName: s3-secret
      name: model
      type: MODEL
```
However, I'm seeing the error 

```
[2019-08-28 17:17:40 +0000] [21] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/microservice/python/seldon_core/microservice.py", line 171, in load
    self.user_object.load()
  File "/microservice/MLFlowServer.py", line 26, in load
    self._model = pyfunc.load_model(model_file)
  File "/usr/local/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 281, in load_model
    return load_pyfunc(model_uri, suppress_warnings)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/annotations.py", line 40, in deprecated_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlflow/pyfunc/__init__.py", line 313, in load_pyfunc
    return importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/usr/local/lib/python3.7/site-packages/mlflow/pyfunc/model.py", line 214, in _load_pyfunc
    python_model = cloudpickle.load(f)
  File "/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1121, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'xgboost'
```

even if I'm having the xgboost included in the conda:

```
channels:
- defaults
dependencies:
- python=3.6.7
- cloudpickle=1.1.1
- pip
- pip:
  - xgboost==0.90
```

Not sure if MLFLOW_SERVER picks the compatible conda environment or is it caused by something else?

**Comment by axsaucedo** [comment]
@lennon310 can you share the code you used to train your model + upload it to s3?

**Comment by lennon310** [comment]
[vanilla_xgboost_preHAC_final_np_full_features.zip](https://github.com/SeldonIO/seldon-core/files/3555237/vanilla_xgboost_preHAC_final_np_full_features.zip)
@axsaucedo Uploaded.

**Comment by axsaucedo** [comment]
@lennon310 thanks for providing the code. I remember that Conda has a limitation with pip packages, which limits its binaries where these are not included/packaged up. Would you be able to try by building the model with the xgboost dependency listed as a Conda dependency instead of pip? 

If you have a look at the implementation of the prepackaged model server, the only thing it does is basically loading the model directly using the `model_uri` link:
https://github.com/SeldonIO/seldon-core/blob/c94d0e9328e3e7eabfe3c2b8faec9d5e7b13a0e3/servers/mlflowserver/mlflowserver/MLFlowServer.py#L26

**Comment by lennon310** [comment]
Thanks @axsaucedo .
I changed the conda file to 

```
channels:
- defaults
dependencies:
- python=3.6.7
- cloudpickle=1.1.1
- xgboost=0.90

name: hh-prehac-xgb-env
```

but still had the same error.

**Comment by lennon310** [comment]
Even if I explicitly write the model class with loading mlflow model: 

```
class Model:
    def __init__(self) -> None:
        self.loaded = False

    def load(self) -> None:
        self.pyfunc_model = pyfunc.load_pyfunc("model")
        self.loaded = True

    def predict(
        self, model_input: np.ndarray, features_names: List[str]
    ) -> np.ndarray:  # noqa: E501
        if not self.loaded:
            self.load()

        if features_names is not None and len(features_names) > 0:
            df = pd.DataFrame(data=model_input, columns=features_names)
        else:
            df = pd.DataFrame(data=model_input)
        return self.pyfunc_model.predict(df)
``` 

and create image with `s2i`, 
I still need to add `xgboost` in `requirement.txt` to avoid the module not found exception (note the xgboost is already defined as dependency in conda in mlflow model)

**Comment by cliveseldon** [comment]
I have not used the mlflow integration extensively but would we not need miniconda as a dependency for the conda environment to be properly handled?

**Comment by axsaucedo** [comment]
@lennon310 as per slack, the [MLFlow pyfunc documentation](https://www.mlflow.org/docs/latest/models.html#python-function-python-function) states that `The python_function model flavor defines a generic filesystem format for Python models and provides utilities for saving and loading models to and from this format. The format is self-contained in the sense that it includes all the information necessary to load and use a model. Dependencies are stored either directly with the model or referenced via Conda environment.`

Based on this, you should be able to load an MLFlow model without having to install the xgboost dependency. I would assume that the reason this can't be done even in the prepackaged model server leads me to believe that there is a step missing whereby the model is not being fully built with all the dependencies as it should be (e.g. you may only be using the model that is generated on each run instead of a model that is packaged up with [MLflow Model API save_model](https://www.mlflow.org/docs/latest/models.html#model-api) interface.

s2i uses docker underneath, so it basically is just creating a clean environment, which means that if you ran the exact same thing locally it would fail - the only reason it would pass is because you currently have all the dependencies, however if you package the model then it should work (based on the MLFlow docs).

Do you see what I mean?

**Comment by lennon310** [comment]
conda.yaml file not used in prepackaged server, that could be the issue

https://github.com/mlflow/mlflow/blob/30a90ec9cbffa5c0d0212368b9f2a7e8c8a3fc81/mlflow/models/container/__init__.py#L102

**Comment by zcharli** [comment]
Documenting what @axsaucedo and I we talked over slack. There are multiple ways this could be addressed
1.  Add a new base image with conda package manager support
2. Load in code at runtime (@axsaucedo to clarify this approach) with a method similar to https://github.com/mlflow/mlflow/blob/ed6fa273e2188ffc5c4673b03857fa1469411598/mlflow/pyfunc/__init__.py#L311
3. Provide additional pip export as part of building the mlflow artifact here: https://github.com/mlflow/mlflow/blob/master/mlflow/pyfunc/model.py#L106

The 3. option would essentially raises the concern for interoperability of libraries across two package managers. Conda can have cross platform binaries that pip does not support.

**Comment by cliveseldon** [comment]
As this seems a more involved fix moving to later milestone.

**Comment by axsaucedo** [comment]
We've had a discussion internally. It seems that a way to potentially address this in the short term, would be allowing for pre-packaged model servers to support a `requirements.txt` file with dependencies. It would then install these dependencies for the model. @zcharli @lennon310 how does this sound?

**Comment by axsaucedo** [comment]
Following up on that, we will first attempt to build a base image with Conda to see if that would provide a cleaner and more aligned way to solve this issue. If that doesn't work we will have the solution with an extra definition of dependencies.
