### ISSUE TITLE
Should seldondeployment generate stable deployment name?

### ISSUE THREAD

**Issue by phsiao** [SeldonIO/seldon-core#851]
Currently seldondeployment would generate deployment name with variable suffix.  For HPA and VPA that can be a problem because both refer to the name of a deployment.  For HPA we can update HPA reference as new deployment is generated; but for VPA, it can be a problem and we can lose historical data that recommend more accurate requested cpu and memory from prior deployments.

For metrics that tied to a deployment name that can be a problem too as we need to coalesce different deployments when we compare the data.

I have not looked into it, but I wonder what are the motivations to use variable deployment names, and whether stable deployment has more values?

**Comment by cliveseldon** [comment]
I agree the naming conventions could be reviewed. At present we build a unique deployment name using the hash of the container images to ensure a new Deployment name is created if you change the images.

https://github.com/SeldonIO/seldon-operator/blob/4dd086e737dff134756c254555e8a9bb7837e657/pkg/apis/machinelearning/v1alpha2/seldondeployment_types.go#L92-L106

**Comment by kparaju** [comment]
@cliveseldon @gsunner I think the deployment name should be generated using the hash of more stuff instead of just the image name. I noticed this issue during load testing while trying to perform bad rollouts. Here are the usecases:

If I change the image name to point to an invalid image: we create a new deployment (old deployment is untouched) with 25% pods as specified in the YAML and since they all ErrImagePullBackOff, traffic is never sent to the new deployment. Works as expected.

If I change the cpu/mem to be very low to force OOMKilled: we create a new replicaset and terminate pods from the existing replicaset. This means that worst case, 50% of pods could be serving 100% of traffic and that leads to 500s. 

If we created a new deployment, it would respect the RollingUpdate strategy and we would have less risk of failures. This also goes for other changes like env vars.
