### ISSUE TITLE
Docker image missing for Iris classification

### ISSUE THREAD

**Issue by krishna-dahifale** [SeldonIO/seldon-core#91]
we are trying to deploy  example which is present on path: seldon-core/examples/models/sklearn_iris.
when we create **sklearn_iris_deployment.json**  giving  error.we are not able to find **seldonio/irisclassifier:0.1** image on DockerHub

**Comment by Maximophone** [comment]
Hi Krishna,

This model has not been pushed as an image on dockerhub because it is meant as an example of wrapping a model and building a docker image locally as per the following [getting started guide](https://github.com/SeldonIO/seldon-core/blob/master/docs/getting_started/minikube.md).

However I noticed that we refer to our docker repository in the image name in this guide, which can be confusing. We will update the guide to make it clearer.
